name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: "0 3 * * 0-6"
  workflow_dispatch:

permissions:
  checks: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Compile and Unit tests (headless for GUI)
        uses: GabrielBB/xvfb-action@v1.6
        with:
          run: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install

      - name: Quality gate
        run: mvn --batch-mode org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Run mutation testing
        run: mvn clean test-compile org.pitest:pitest-maven:mutationCoverage

      - name: Check test strength
        uses: teemoo7/mutation-testing-report-action@Mutation-testing-pitest
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
